version: "3"
services:
  db:
    image: postgres
  redis:
    image: redis
    ports:
    - "6379:6379"
  web:
    build: .
    command: bin/rails server --port 3001 --binding 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    links:
    - "db:db"
    depends_on:
      - db